/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FastTrackRouteImport } from './routes/fast-track'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as CoursesUndergraduateRouteImport } from './routes/courses.undergraduate'
import { Route as CoursesShortCoursesRouteImport } from './routes/courses.short-courses'
import { Route as CoursesPostgraduateRouteImport } from './routes/courses.postgraduate'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AboutWhyLbcRouteImport } from './routes/about.why-lbc'
import { Route as AboutWhoWeAreRouteImport } from './routes/about.who-we-are'
import { Route as AboutRecognitionRouteImport } from './routes/about.recognition'
import { Route as AboutAssignmentLearningRouteImport } from './routes/about.assignment-learning'
import { Route as AboutAdmissionRouteImport } from './routes/about.admission'
import { Route as AboutAccreditationRouteImport } from './routes/about.accreditation'

const FastTrackRoute = FastTrackRouteImport.update({
  id: '/fast-track',
  path: '/fast-track',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const CoursesUndergraduateRoute = CoursesUndergraduateRouteImport.update({
  id: '/undergraduate',
  path: '/undergraduate',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesShortCoursesRoute = CoursesShortCoursesRouteImport.update({
  id: '/short-courses',
  path: '/short-courses',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesPostgraduateRoute = CoursesPostgraduateRouteImport.update({
  id: '/postgraduate',
  path: '/postgraduate',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AboutWhyLbcRoute = AboutWhyLbcRouteImport.update({
  id: '/why-lbc',
  path: '/why-lbc',
  getParentRoute: () => AboutRoute,
} as any)
const AboutWhoWeAreRoute = AboutWhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => AboutRoute,
} as any)
const AboutRecognitionRoute = AboutRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAssignmentLearningRoute = AboutAssignmentLearningRouteImport.update({
  id: '/assignment-learning',
  path: '/assignment-learning',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAdmissionRoute = AboutAdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAccreditationRoute = AboutAccreditationRouteImport.update({
  id: '/accreditation',
  path: '/accreditation',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/fast-track': typeof FastTrackRoute
  '/about/accreditation': typeof AboutAccreditationRoute
  '/about/admission': typeof AboutAdmissionRoute
  '/about/assignment-learning': typeof AboutAssignmentLearningRoute
  '/about/recognition': typeof AboutRecognitionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/about/why-lbc': typeof AboutWhyLbcRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/postgraduate': typeof CoursesPostgraduateRoute
  '/courses/short-courses': typeof CoursesShortCoursesRoute
  '/courses/undergraduate': typeof CoursesUndergraduateRoute
  '/about/': typeof AboutIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/fast-track': typeof FastTrackRoute
  '/about/accreditation': typeof AboutAccreditationRoute
  '/about/admission': typeof AboutAdmissionRoute
  '/about/assignment-learning': typeof AboutAssignmentLearningRoute
  '/about/recognition': typeof AboutRecognitionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/about/why-lbc': typeof AboutWhyLbcRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/postgraduate': typeof CoursesPostgraduateRoute
  '/courses/short-courses': typeof CoursesShortCoursesRoute
  '/courses/undergraduate': typeof CoursesUndergraduateRoute
  '/about': typeof AboutIndexRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/fast-track': typeof FastTrackRoute
  '/about/accreditation': typeof AboutAccreditationRoute
  '/about/admission': typeof AboutAdmissionRoute
  '/about/assignment-learning': typeof AboutAssignmentLearningRoute
  '/about/recognition': typeof AboutRecognitionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/about/why-lbc': typeof AboutWhyLbcRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/postgraduate': typeof CoursesPostgraduateRoute
  '/courses/short-courses': typeof CoursesShortCoursesRoute
  '/courses/undergraduate': typeof CoursesUndergraduateRoute
  '/about/': typeof AboutIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/faqs'
    | '/fast-track'
    | '/about/accreditation'
    | '/about/admission'
    | '/about/assignment-learning'
    | '/about/recognition'
    | '/about/who-we-are'
    | '/about/why-lbc'
    | '/courses/$courseId'
    | '/courses/postgraduate'
    | '/courses/short-courses'
    | '/courses/undergraduate'
    | '/about/'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faqs'
    | '/fast-track'
    | '/about/accreditation'
    | '/about/admission'
    | '/about/assignment-learning'
    | '/about/recognition'
    | '/about/who-we-are'
    | '/about/why-lbc'
    | '/courses/$courseId'
    | '/courses/postgraduate'
    | '/courses/short-courses'
    | '/courses/undergraduate'
    | '/about'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/faqs'
    | '/fast-track'
    | '/about/accreditation'
    | '/about/admission'
    | '/about/assignment-learning'
    | '/about/recognition'
    | '/about/who-we-are'
    | '/about/why-lbc'
    | '/courses/$courseId'
    | '/courses/postgraduate'
    | '/courses/short-courses'
    | '/courses/undergraduate'
    | '/about/'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  FastTrackRoute: typeof FastTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fast-track': {
      id: '/fast-track'
      path: '/fast-track'
      fullPath: '/fast-track'
      preLoaderRoute: typeof FastTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/courses/undergraduate': {
      id: '/courses/undergraduate'
      path: '/undergraduate'
      fullPath: '/courses/undergraduate'
      preLoaderRoute: typeof CoursesUndergraduateRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/short-courses': {
      id: '/courses/short-courses'
      path: '/short-courses'
      fullPath: '/courses/short-courses'
      preLoaderRoute: typeof CoursesShortCoursesRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/postgraduate': {
      id: '/courses/postgraduate'
      path: '/postgraduate'
      fullPath: '/courses/postgraduate'
      preLoaderRoute: typeof CoursesPostgraduateRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/about/why-lbc': {
      id: '/about/why-lbc'
      path: '/why-lbc'
      fullPath: '/about/why-lbc'
      preLoaderRoute: typeof AboutWhyLbcRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/who-we-are': {
      id: '/about/who-we-are'
      path: '/who-we-are'
      fullPath: '/about/who-we-are'
      preLoaderRoute: typeof AboutWhoWeAreRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/recognition': {
      id: '/about/recognition'
      path: '/recognition'
      fullPath: '/about/recognition'
      preLoaderRoute: typeof AboutRecognitionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/assignment-learning': {
      id: '/about/assignment-learning'
      path: '/assignment-learning'
      fullPath: '/about/assignment-learning'
      preLoaderRoute: typeof AboutAssignmentLearningRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/admission': {
      id: '/about/admission'
      path: '/admission'
      fullPath: '/about/admission'
      preLoaderRoute: typeof AboutAdmissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/accreditation': {
      id: '/about/accreditation'
      path: '/accreditation'
      fullPath: '/about/accreditation'
      preLoaderRoute: typeof AboutAccreditationRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutAccreditationRoute: typeof AboutAccreditationRoute
  AboutAdmissionRoute: typeof AboutAdmissionRoute
  AboutAssignmentLearningRoute: typeof AboutAssignmentLearningRoute
  AboutRecognitionRoute: typeof AboutRecognitionRoute
  AboutWhoWeAreRoute: typeof AboutWhoWeAreRoute
  AboutWhyLbcRoute: typeof AboutWhyLbcRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAccreditationRoute: AboutAccreditationRoute,
  AboutAdmissionRoute: AboutAdmissionRoute,
  AboutAssignmentLearningRoute: AboutAssignmentLearningRoute,
  AboutRecognitionRoute: AboutRecognitionRoute,
  AboutWhoWeAreRoute: AboutWhoWeAreRoute,
  AboutWhyLbcRoute: AboutWhyLbcRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesPostgraduateRoute: typeof CoursesPostgraduateRoute
  CoursesShortCoursesRoute: typeof CoursesShortCoursesRoute
  CoursesUndergraduateRoute: typeof CoursesUndergraduateRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesPostgraduateRoute: CoursesPostgraduateRoute,
  CoursesShortCoursesRoute: CoursesShortCoursesRoute,
  CoursesUndergraduateRoute: CoursesUndergraduateRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FaqsRoute: FaqsRoute,
  FastTrackRoute: FastTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
